### ISSUE TITLE
Make it easier to add a process to a cgroup

### ISSUE THREAD

**Issue by EdorianDark** [ordovicia/controlgroup-rs#20]
The builder example looks very impressive, but i struggle to struggle to add a process to a cgroup.
Something like an [extension for std::process::Command](https://docs.rs/cgroups-fs/1.1.1/cgroups_fs/trait.CgroupsCommandExt.html#impl-CgroupsCommandExt) would be nice.

**Comment by ordovicia** [comment]
Hi. Thank you for looking at this repository!

You can add a process to a cgroup in this way:

```rust
let mut cgroups = Builder::new(PathBuf::from("cgroup-test"))
    .cpu()
        .shares(1000)
        .done()
    .build()?;

let child = Command::new("sleep").arg("8").spawn().unwrap();
let pid = Pid::from(&child);
cgroups.add_proc(pid)?;
```

But I've just realized that the process is added to the cgroup *after* it's spawned.
I guess you want to add a process before it's spawned?
I'll add functionality for that, or your PR will be much welcomed!

**Comment by EdorianDark** [comment]
Yes, I want to spawn a process inside the cgroup

**Comment by EdorianDark** [comment]
It could look like that:
```rust
pub trait CGroupCommandExt {
    fn cgroup(&mut self, group: &mut UnifiedRepr) -> &mut Self;
}

impl CGroupCommandExt for std::process::Command{

    fn cgroup(&mut self, group: &mut UnifiedRepr) -> &mut Self    {
        unsafe{
            self.pre_exec(|| {
                let pid = crate::Pid::from(std::process::id());
                group.add_proc(pid)
            });
        }
        self
    }
```
I implemented it in v1/builder.rs. The remaining problem is to convert the error, but i am not sure how to do that best

**Comment by ordovicia** [comment]
It would be better to allow the `cgroup` method in the extension trait take `Subsystem`s (e.g. `v1::cpu::Subsystem`) as well as `UnifiedRepr`.
We would need to define a trait (say `AddProcIo`) for the operation of adding a process and implement it for `UnifiedRepr` and `Subsystem`s.

> The remaining problem is to convert the error, but i am not sure how to do that best

One solution is implementing the method in `AddPrioIo` to return `std::io::Result<()>`, by extracting the `std::fs::write()` call from `Cgroup::add_proc()`.
`Cgroup::add_proc()` can just call the `AddPrioIo` method and convert `Err`.

```rust
pub trait AddProcIo { // there may be a better name
    fn add_proc_io(&mut self, pid: impl Into<Pid>) -> std::io::Result<()>;
}

pub trait Cgroup: AddProcIo {
    // ...

    fn add_proc(&mut self, pid: impl Into<Pid>) -> Result<()> {
        self.add_proc_io(pid).map_err(Into::into)
    }
}
```
