### ISSUE TITLE
Maybe implement Drop on CGroup

### ISSUE THREAD

**Issue by EdorianDark** [ordovicia/controlgroup-rs#21]
I think it would be better, if the cgroup in the example would clean after itself.
```
let mut cgroup = cpu::Subsystem::new(
    CgroupPath::new(SubsystemKind::Cpu, PathBuf::from("students/charlie")));
cgroup.create()?;
[...]
cgroup.delete()?; //That could be done automatically
```

**Comment by ordovicia** [comment]
`Subsystem::new()` itself does not create a directory for the cgroup.
It just defines a handler for the cgroup.
(`create()` does create the directory.)

In some cases a cgroup has to remain alive after a `Subsystem`s drops, so we cannot implement `Drop` for deleting the cgroup directory.
