### ISSUE TITLE
Linux namespaces

### ISSUE THREAD

**Issue by EdorianDark** [ordovicia/controlgroup-rs#23]
I didn't find documentation how integrate controlgroup-rs with namespaces.
I think it makes lot of sense to use [namespaces](http://man7.org/linux/man-pages/man7/pid_namespaces.7.html) to constrain subproceses further or document a possible integration.

**Comment by ordovicia** [comment]
Hi. Thank you for the comment!

cgroups and Linux namespaces are separate features (though they are typically used together in container engine implementations, of course).
`controlgroup-rs` is just for operations on cgroups.
Some other programs will be needed to handle namespaces, but I do not plan to integrate such functionality to this crate.
